### ISSUE TITLE
New algorithim API paradigms: n-ary algorithms (ex: for_each, transform), range-based algorithms and (multi-)index-based algorithms

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#107]
`for_each` only takes one input range, and `transform` takes up to two input ranges. These choices seem pretty arbitrary (though in `transform`'s case, the choice seems to be motivated by `<functional>`'s binary operations) and force the user to involve `make_zip_iterator(make_tuple(...))` awkwardly for simple operations. We could generalize both of these pretty easily.

**Comment by andrewcorrigan** [comment]
This is useful and would reduce my reliance on ```make_zip_iterator(make_tuple(...))``` and the need to unpack arguments from tuples, so I am currently implementing my own versions of these.  I just want to be sure I follow the same interface that you would eventually use.

Would you use variadic templates for this?  What would the interface for these be?   Would you put all the extra input iterators at the end of the argument list?

```
template<typename DerivedPolicy , typename InputIterator1 , typename OutputIterator , typename BinaryFunction , typename... InputIterators>
__host__ __device__ OutputIterator 	thrust::transform (
    const thrust::detail::execution_policy_base< DerivedPolicy > &exec,
    InputIterator1 first1,
    InputIterator1 last1,
    OutputIterator result,
    BinaryFunction op,
    InputIterators... firsts)
```

Or would you keep the first two at the beginning for compatibility with the existing binary transform?
```
template<typename DerivedPolicy , typename InputIterator1 , typename InputIterator2 , typename OutputIterator , typename BinaryFunction , typename... InputIterators>
__host__ __device__ OutputIterator 	thrust::transform (
    const thrust::detail::execution_policy_base< DerivedPolicy > &exec,
    InputIterator1 first1,
    InputIterator1 last1,
    InputIterator2 first2,
    OutputIterator result,
    BinaryFunction op,
    InputIterators... firsts)
```

Or something else, like for example explicitly enumerating all the options without variadic templates, so that the arguments could be like: `(first1, last1, first2, first3, first4, result, op)`?

**Comment by jaredhoberock** [comment]
The function object would need to come last just like the existing algorithms. Putting the extra ranges at the end after the function would be too goofy to use I think.

**Comment by brycelelbach** [comment]
From #856, a related request: four-input transform.


```
#include <thrust/device_vector.h>
#include <thrust/transform.h>
struct four_input
{
  __host__ __device__
  double operator()(const double &a,const double &b,const double &c,const double &d) const {
      return a*b*c*d;
  }
}; 
int main(void)
{
    thrust::device_vector<double> A(10);
    thrust::device_vector<double> B(10);
    thrust::device_vector<double> C(10);
    thrust::device_vector<double> D(10);
    thrust::device_vector<double> out(10);
    thrust::transform(A.begin(), A.end(), B.begin(), C.begin(), D.begin(), out.begin(), four_input());
    return 0;    
}
```

As a reformed SIMD programmer, I'm not a huge fan of zip_iterator, because it imposes a certain data layout. I'm not sure if n-ary forms help with that any, but I agree they'd be nice to have.

Also, something in the space of (multi)index-based overloads (similar to the [the for_loop](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0075r1.pdf) proposal, or my own [mdspan madness](https://github.com/brycelelbach/mdspan)) would be nice as well - people use counting_iterator and constant_iterator as crutches because they don't have them.

One nice benefit of moving away from the utility iterators - we'd get less bug reports for them.

**Comment by brycelelbach** [comment]
My guess is that we should approach this from a broader scope; e.g. consider all of the parallel algorithms and come up with a coherent strategy, instead of making piecemeal improvements.

**Comment by Slaedr** [comment]
Perhaps I'm missing something here, but just a thought - at some point, shouldn't a more [Kokkos](https://github.com/kokkos)-like model be preferred? All the required arrays are passed by reference to the constructor of the functor, and the references are stored in the functor as members. Then, the simple `for_each` is enough - we just use a `counting_iterator<index>` as the range. In the `operator(const index i)` function of the functor, we can access all the arrays we need using the member references. As far as I can see, this is already possible in Thrust.

In case lambdas are allowed, all the arrays can just caught by reference.

**Comment by jrhemstad** [comment]
I think in a post-ranges world all of this would be done with a zip_view.
