### ISSUE TITLE
Support noexcept for Feta greatness

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/thrust#1147]
If we have a no except mode, Feta can turn on `-fno-exceptions`.

If Feta can turn on `-fno-exceptions`, `std::string` code can compile with Feta.

If `std::string` code compile with Feta, the only road block to this is figuring out how to allocate managed memory in device code:

```
#include <string>
#include <vector>
#include <numeric>
#include <execution>
#include <iostream>

int main() {
  std::vector<std::string> strings;

  strings.push_back("hello ");
  strings.push_back("world ");
  strings.push_back("from ");
  strings.push_back("DGX ");
  strings.push_back("A100!");

  std::inclusive_scan(std::execution::par,
                      strings.begin(), strings.end(), strings.begin());

  for (auto&& s : strings) std::cout << s << std::endl;
}
```

I desperately want the above code to compile. So the first step is us supporting `-fno-exceptions`.

A man can dream...

**Comment by allisonvacanti** [comment]
I don't know if this is a great idea...I already see a ton of issues trying to build this with Feta:

![image](https://user-images.githubusercontent.com/58744/82065403-0e778580-969c-11ea-87ef-0d75010d297a.png)

**Comment by dkolsen-pgi** [comment]
`g++ -fno-exceptions` gives compile-time errors when it encounters a `throw` expression or a `catch` block.  `nvc++ --no_exceptions` quite reasonably has a similar behavior.  If you want to support a no-exceptions mode in Feta, then I see two possible approaches:
1. Edit the Thrust headers and the Feta headers to wrap all `throw` expressions and `catch` blocks in `#if __EXCEPTIONS`
2. Add a new option to `nvc++`, such as `--ignore_exceptions`, which turns off exception handling.  But rather than a compiler error, `throw` expressions are compiled as a call to `std::terminate()` and `catch` block are ignored.

**Comment by dkolsen-pgi** [comment]
No, I don't think asking Thrust to support compiling in a mode where `throw` expressions and `try` blocks are compiler errors is still relevant.  If we really want to support Thrust with no exceptions the best approach is to change `nvc++` so that exception constructs are ignored rather than a compilation error.  That hopefully wouldn't require changes to Thrust code.  But I don't think that even that is worth doing.

The biggest barrier to Bryce's dream of building long `std::string`s in device code is allocating host-visible memory from device code.  I don't see how to get past that.  Without that, the effort of supporting no-exceptions mode in host code is not worth it.

**Comment by jrhemstad** [comment]
Alright, closing this and we can open new issues as needed.
