### ISSUE TITLE
Cub submodule is incorrect

### ISSUE THREAD

**Issue by r-barnes** [NVIDIA/thrust#1307]
Cub is currently assumed to be located on the user's computer, rather than included as a submodule.

This contradicts `CONTRIBUTING.md`, which says that `git clone --recursive` is sufficient to get Thrust and its dependencies.

**Comment by griwes** [comment]
This is incorrect. The current submodule uses a relative submodule reference, to allow us to have mirrors on more than Github, so that clones from any of the mirror work by cloning both repositories from the mirror. It has the side effect of requiring a fork you want to clone to have a sister CUB repo in the same place in the hierarchy as Thrust, yes, but it also enables us to have both an external and an internal Thrust+CUB repository pairs.

See [the section on `git submodule add` in the docs](https://git-scm.com/docs/git-submodule).

**Comment by r-barnes** [comment]
My bad; perhaps the instructions in CONTRIBUTING were unclear to me. I'll close.
