### ISSUE TITLE
out-of-bounds

### ISSUE THREAD

**Issue by 3gx** [NVIDIA/thrust#1446]
I think https://github.com/NVIDIA/thrust/blob/main/thrust/system/cuda/detail/sort.h#L123 may result in OOB access when the last element of the keys2 array is processed. Perhaps this load can be guarded with `if (keys2_beg < keys2_end) {  key2 = keys_shared[keys2_beg]; }`

**Comment by allisonvacanti** [comment]
@senior-zero can you take a look at this one? It does look suspicious since the iterators are conditionally incremented a few lines above.

**Comment by senior-zero** [comment]
Hello @3gx!

Thank you for your concern. I've checked the code and haven't found the out of boundary access. Here is the logic behind this statement. 

`keys_shared` is a pointer to `storage.keys_shared`. The size of `storage.keys_shared` is equal to `PtxPlan::ITEMS_PER_TILE + 1` where `PtxPlan::ITEMS_PER_TILE = _BLOCK_THREADS * _ITEMS_PER_THREAD`. For simplicity, let's stick to some values. I'll assume that the `BLOCK_THREADS=32` and the `ITEMS_PER_THREAD=15`. In this case, the size of the `storage.keys_shared` is exactly `32 * 15 + 1`, i.e. 481 elements. The loop that you pointed out has exactly `ITEMS_PER_THREAD=15` iterations. Therefore the `keys2_beg` can be incremented at most 15 times. 

If the last element of the second range is processed, the `keys2_beg` value matches `keys2_end` indeed. But as long as `keys2_end` doesn't exceed `ITEMS_PER_TILE = 480`, there is no out of boundary access because there are `ITEMS_PER_TILE + 1 = 481` elements allocated.  Moreover, the compiler manages to optimize statements without side effects. I've written a small code snippet to illustrate this. You can check it [here](https://cuda.godbolt.org/z/T4rjcEr4b). As you can see, there are only `N - 1` function calls generated. 

The only thing that's left to show is that the `keys2_end` doesn't exceed `ITEMS_PER_TILE`. Effectivly `keys2_end_loc = (((ITEMS_PER_THREAD * list) + size) + size)` where `list = 32 - coop` for the last thread and `size = ITEMS_PER_THREAD * (coop >> 1)`. `coop` is a powers of two sequence in range `[2, BLOCK_THREADS]`. So for the last thread `keys2_end` can be expressed as the following statement:

![image](https://user-images.githubusercontent.com/9890394/120635374-148dff00-c475-11eb-8871-91131b168bff.png)

So `keys2_end` doesn't depend on `coop` for the last thread. `keys2_end` doesn't exceed `ITEMS_PER_TILE` and there is no out of boundary access. Please let me know if there is anything I'm missing. Otherwise, I suggest closing the issue.

**Comment by senior-zero** [comment]
I'm closing the issue. However, if you find that the OOB access happens in your case, please feel free to reopen it.
