### ISSUE TITLE
There is NOWhere in CMakeLists.txt to specify system TBB and system OMP ?????

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA/thrust#1494]
```console
-- CPP system found?  TRUE
-- CUDA system found? TRUE
-- TBB system found?  FALSE
-- OMP system found?  FALSE
```

**Comment by allisonvacanti** [comment]
Thrust is a header only library, there's no need to build the Thrust project as a user. Those messages are only printed when building the developer test suite.

I suggest looking at the first section of our `README.md` file, [which explains how to setup your project to use Thrust](https://github.com/NVIDIA/thrust/blob/main/README.md#quick-start-using-thrust-from-your-project). Since you're interested in using a non-CUDA backend from CMake, you'll probably find the linked [CMake package documentation](https://github.com/NVIDIA/thrust/blob/main/thrust/cmake/README.md) useful.

If you are intentionally compiling the test suite, the CMake options for the developer build are documented in our [contributing guide](https://github.com/NVIDIA/thrust/blob/main/CONTRIBUTING.md#cmake-options).

**Comment by jiapei100** [comment]
@allisonvacanti 

So, are you saying that if CUDA is enabled, TBB and OMP will be disabled by default? 
I surely expect using a CUDA enabled environment. But, I was thinking it could be possible that OMP is also able to be found.

**Comment by allisonvacanti** [comment]
By default, the host system will be CPP (serial), and the device system will be CUDA accelerated. Both of these can be changed using the options in the provided documentation. The host system can be set to OMP and the device system can be set to CUDA to enable the configuration you describe -- in this configuration, host execution will be OpenMP accelerated, while device execution will use CUDA acceleration.
