### ISSUE TITLE
Add unique_count algorithm

### ISSUE THREAD

**Issue by upsj** [NVIDIA/thrust#1612]
For the common *count* -> allocate -> *fill* pattern (e.g. `count_if`/`copy_if`) there are some fill algorithms without a corresponding count algorithm, mainly `unique_copy`, `unique_by_key_copy` and `reduce_by_key`. So I want to suggest adding a `count_unique` algorithm with basically the same interface as `unique` save the return type:
```cpp
difference_type thrust::count_unique(
        Policy exec,
        ForwardIterator first,
        ForwardIterator last,
        BinaryPredicate binary_pred)
```

The name probably needs a bit of discussion, since it doesn't actually count unique elements, but runs of unique elements, but `unique` has the same issue, so there is some prior art for it.

@allisonvacanti suggested using [`cub::DeviceRunLengthEncode::Encode`](https://nvlabs.github.io/cub/structcub_1_1_device_run_length_encode.html) to implement it, so I wanted to check whether there are any other approaches to consider before starting work on a PR. Another simple approach might be
```cpp
auto zip_it = zip(it, it + 1);
if (size > 0) {
    return 1 + count_if(zip_it, zip_it + size - 1, [](auto a) { !binary_pred(get<0>(a), get<1>(a)); });
} else {
    return 0;
}
```

**Comment by jrhemstad** [comment]
CC @codereport on naming bikeshedding. I'd advocate for `unique_count` so it sorts next to the other `unique_*` algorithms.

I suppose `cub::DeviceRunLengthEncode::Encode/NonTrivialRuns` with discard iterators for the unique values/counts would work. I'd benchmark it against just doing `count_if`.

**Comment by codereport** [comment]
Long story short, I agree with @jrhemstad, `unique_count` is the correct name.

----

More details: we sort of had the opposite issue at one point in RAPIDS. We had an algorithm/API called `unique_count` but it was really not the right name in the C++ sense because it was counting the number of "unique" (**not** in the C++ sense) elements. Basically the equivalent in Python is:
```py
def unique_count(list):
   return len(set(list))
```
We ended up changing the name to [`distinct_count`](https://docs.rapids.ai/api/libcudf/stable/group__reorder__compact.html#gab6e12738145f070878194502d8d5a1c9).

**Comment by upsj** [comment]
I will go with `unique_count` then. Should this be part of a new header or in `unique`/`unique_by_key`? Also it looks like `head_flags` already provides the necessary zip functionality wrapped neatly.
