### ISSUE TITLE
`scan_by_key` optimization with `discard_iterator`

### ISSUE THREAD

**Issue by pauleonix** [NVIDIA/thrust#1710]
When looking at the [implementation](https://github.com/NVIDIA/thrust/blob/main/thrust/system/detail/generic/scan_by_key.inl#L96-L135) of `inclusive_scan_by_key`:
```c++
thrust::inclusive_scan(exec,
                       thrust::make_zip_iterator(thrust::make_tuple(first2, flags.begin())),
                       thrust::make_zip_iterator(thrust::make_tuple(first2, flags.begin())) + n,
                       thrust::make_zip_iterator(thrust::make_tuple(result, flags.begin())),
                       detail::segmented_scan_functor<OutputType, HeadFlagType, AssociativeOperator>(binary_op));
```
and `exclusive_scan_by_key`, I noticed, that there are unnecessary writes to `flags`. Wouldn't it make more sense to use a `discard_iterator` here to avoid these writes?

**Comment by senior-zero** [comment]
Hello @pauleonix! Your suggestion is correct, it should be sufficient to write:
```cpp
thrust::inclusive_scan(exec,
                       thrust::make_zip_iterator(thrust::make_tuple(first2, flags.begin())),
                       thrust::make_zip_iterator(thrust::make_tuple(first2, flags.begin())) + n,
                       thrust::make_zip_iterator(thrust::make_tuple(result, thrust::make_discard_iterator())),
                       detail::segmented_scan_functor<OutputType, HeadFlagType, AssociativeOperator>(binary_op));
```

The only issue with that is related to the fact that none of the Thrust execution policies are using this code. Our CUDA backend is using CUB implementation, while TBB and OMP policies are relying on sequential code. Therefore, we won't be able to verify the change. I'm closing this issue as not planned, since I don't see reasons to optimize dead code. If you have a use-case that triggers this code usage, please, feel free to reopen.

**Comment by pauleonix** [comment]
@senior-zero I guess one could argue that a discard iterator would also improve general legibility as it shows intention, but as the generic code is not used for documentation purposes, I don't think it is of any importance. I don't know anymore if it was clear to me at the time of writing that this was dead code - probably not.
