### ISSUE TITLE
`thrust::complex` divided by `int`

### ISSUE THREAD

**Issue by kanglcn** [NVIDIA/thrust#1847]
Hi, I find `thrust::operator/ (const complex< T0 > &  x, const T1 & y)` can not handle the case when `T0` is `float` and `T1` is `int`. I have to cast `T1` to `float` explicitly which is not intuitive.

I am working on speeding up my python code with cupy elementwise kernel. I have no experience on c++ before so I cannot provide an example. Sorry about that.

**Comment by jrhemstad** [comment]
This by design as `thrust::complex` is intended to be consistent with `std::complex`: https://godbolt.org/z/d4oGb3xMs

The `operator/` is only defined for a `complex<T>` when dividing by a `T` scalar:
```
template< class T >
constexpr std::complex<T> operator/(const std::complex<T>& lhs, const T& rhs );
```

If you're wondering why the conversion from `int` to `float` doesn't happen implicitly, it's because `lhs` is in a "deduced context", which means the template type `T` is deduced from the type of `rhs` and `lhs` and the `T` needs to match between the two.

**Comment by kanglcn** [comment]
Thanks a lot!
