### ISSUE TITLE
make thrust::detail::head_flags / tail_flags part of thrust's public interface

### ISSUE THREAD

**Issue by schiller-manuel** [NVIDIA/thrust#681]
Finding begin and end of segments is a common problem.

Could `thrust::detail::head_flags` and `thrust::detail::tail_flags` be made "publicly" available instead of residing in the "hidden" `namespace detail`?

**Comment by jaredhoberock** [comment]
I'm not sure it's that common -- I don't recall it ever coming up on the thrust-users mailing list, for example. There are other examples of things like this that are more common which are not part of the interface -- `strided_range` comes to mind.

I do think it would make for a good pedagogical example program, though, if the current implementation was simplified. If you cooked up a nice well-motivated example program that needed to use these components, I would accept it into the suite of example programs. That would make it easy to link to a recipe demonstrating how to build and use it and also ensure that the implementation is quasi-supported.

**Comment by dachziegel** [comment]
Well for me it is a common use case. I do even have a problem (+solution :) ) which could make a nice example program: 

http://stackoverflow.com/a/31221858/678093

`my_scatter` is very similar to `head_flags`, however it gives the index of the begin of a segment rather than a boolean result.

**Comment by jaredhoberock** [comment]
After looking at the other similar example programs (`repeated_range.cu` & `strided_range.cu`), on second thought I think the example should just focus on explaining the implementation of `head_flags` (to keep it simple, I'd just demonstrate this one class) rather than try to apply it to some particular use case. The composition of fancy iterators inside the class is subtle enough that it will require some exposition. Additionally introducing some non-trivial use case in addition is too much complexity for an example program.

So I would focus on clearly explaining the implementation of the class and then do some simple operations with it. For example, the `main` function could print out the value of each flag element, and maybe their positions. You could also demonstrate a transformation, for example, replacing the value of each flag element with some other value.

**Comment by dachziegel** [comment]
should this example mention the fact that it is based on `thrust::detail::head_flags`? but this might be tempting to just include that private header.

**Comment by jaredhoberock** [comment]
No, there's no reason to.
