### ISSUE TITLE
CUDA profiler hooks

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#81]
When profiling Thrust applications with tools like the CUDA Visual Profiler or Parallel Nsight it would be useful to have algorithms reported in a more straightforward way.  Specifically, rather than having each individual kernel, with their lengthly mangled names, appear in the profile it would be preferable to have simple expressions like `thrust::sort` or perhaps `thrust::sort<FooIterator>`.

Ideally the tools above would support some sort of stack-based mechanism to aggregate and nest kernels into logical algorithms.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=251

**Comment by rconnorlawson** [comment]
I just want to note that this issue is still relevant, and I also would like to see this feature added. My use case is this: I'm currently struggling to isolate a call to `scatter_if` in the profiler output. I believe it is reported as one of many `ParallelForAgent` kernels on the CUB backend, but the name `scatter_if` isn't present in the profiler output at all. Profiler keys would remove this issue entirely.

I'm not sure how these kinds of debugger/profiler hooks work or what is possible, but I'm certain that some algorithms (such as `sort` and `reduce_by_key`) require multiple kernel calls to execute. Grouping those kernels together per thrust API call would be extremely helpful to get a better picture of the hotspots in the code.

**Comment by jrhemstad** [comment]
Closing in favor of https://github.com/NVIDIA/thrust/issues/1012
