### ISSUE TITLE
Does thrust::inclusive_scan will synchronize with other CUDA streams?

### ISSUE THREAD

**Issue by StrikeW** [NVIDIA/thrust#905]
I called `thrust::inclusive_scan` with its first arg as `thrust::cuda::par.on(stream_id)`, but it seems that it doesn't execute concurrently with other `cudaMemcpyAsnc()` in other stream. I want to know exactly in what conditions `thrust::inclusive_scan` will synchronize with other CUDA streams?

**Comment by brycelelbach** [comment]
Can you provide some more details about your environment? See https://github.com/brycelelbach/cpp_bug_reporting_guidelines.

In particular, are you using a system with multiple GPUs that support peer mappings?

If so, this may be a known design defect in Thrust. The issue is that the core Thrust primitives (sorting, reductions and scans) all need to allocate temporary storage to be efficiently parallelized. Thrust has a system for temporary memory allocation, similar to `std::get_temporary_buffer`/`std::return_temporary_buffer`. By default, Thrust will allocate/deallocate temporary storage with `cudaMalloc`/`cudaFree`. There is some rudimentary for controlling the allocator used for these temporary allocations by attaching an allocator to an execution policy. See:

https://github.com/thrust/thrust/blob/master/examples/cuda/custom_temporary_allocation.cu

This is problematic because `cudaMalloc` and `cudaFree` may implicitly synchronize (potentially with all devices in the system). `cudaFree` is the big culprit (which is good, in a way, because it's easier to defer freeing memory than it is to defer allocating memory), but `cudaMalloc` can synchronize as well. `cudaMalloc` will synchronize the current device and with all peer devices that have peer mappings setup (i.e. `cuCtxPeerEnable` / `cudaDevicePeerEnable`). If you don't enable peers, or lazily enable them, the `cudaMalloc` call won't synchronize with those devices to the best of my knowledge.

I suspect this is the issue you're running into.

Today, you can avoid this implicit synchronization by using a caching allocator like the one linked above. In the (near) future, we'll have a solution for this in Thrust's API.

Longer term, Thrust's current support for asynchronous invocation and allocator support has a number of issues. We're planning to address these shortcomings in the future.

**Comment by StrikeW** [comment]
Thanks for your detailed explanation.
My machine does have two GPUs (Tesla K40m) and Thrust version is 1.8.3, but I do not enable **Peer Access** and I only use GPU0 by calling `cudaSetDevice(0)`. If Thrust use `cudaMalloc` and `cudaFree` during scan, it will cause [Implicit synchronization](https://devtalk.nvidia.com/default/topic/829032/implicit-synchronization/) between streams. But the [doc](https://thrust.github.io/doc/group__prefixsums.html#gafb24ad76101263038b0acaddc094d70a) doesn't offer this information to users, at least I didn't found any description about **temporary storage**.

**Comment by brycelelbach** [comment]
Can you provide a minimal test case?

Take a look at https://github.com/brycelelbach/cpp_bug_reporting_guidelines for guidance.
