### ISSUE TITLE
complex list initialization error in 9.2

### ISSUE THREAD

**Issue by judfs** [NVIDIA/thrust#930]
```
#include <thrust/complex.h>
#include <iostream>

int main(){
    std::cout << "hello \n";

//    thrust::complex<float> a(1,2); //fine

    thrust::complex<float> b{3,4}; // fine 

    b = {5,6}; // error

    std::cout << "meow \n";
    return 0;
}
```
Worked with 9.1 but `nvcc -std=c++11 foo.cu` fails on 9.2 with 
```
foo.cu(11): error: more than one operator "=" matches these operands:
            function "thrust::complex<T>::operator=(const thrust::complex<T> &) [with T=float]"
            function "thrust::complex<T>::operator=(const std::complex<T> &) [with T=float]"
            operand types are: thrust::complex<float> = {...}

1 error detected in the compilation of "/tmp/tmpxft_00006bce_00000000-8_foo.cpp1.ii".
```
Centos 7
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Built on Tue_Jun_12_23:07:04_CDT_2018 Cuda compilation tools, release 9.2, V9.2.148

**Comment by griwes** [comment]
`b = {5, 6};` is actually copy assignment, and not list initialization. That line fails, because `thrust::complex<T>` seems to be overeager defining assignment operators from `std::complex`, defining both an assignment operator template from a `std::complex` for an arbitrary type, but *also*, for some reason, from `std::complex<T>`, which makes the disambiguation rules of the language decide that the code is incorrect (see what happens [in an analogous case](https://godbolt.org/z/5TNJ0S) when you uncomment the non-template assignment from `complex1`).

@brycelelbach the fix seems to be just removing one superfluous overload of `operator=`; does that seem correct to you?

**Comment by griwes** [comment]
@jaredhoberock yes, I know that - but `thrust::complex<T>` has both an assignment operator from `std::complex<U>` (this one's a template) **and** an assignment operator from `std::complex<T>` - this one *isn't* an operator and is an equally good candidate for `b = {5, 6};` as the assignment operator from `thrust::complex<T>`. If we just remove the non-template assignment operator from `std::complex<T>`, the problem disappears, and the functionality is preserved (because you can still assign using the templated version). See the linked godbolt; `complex1` is equivalent to `std::complex`, and `complex2` is equivalent to `thrust::complex`.

**Comment by jrhemstad** [comment]
We will be replacing `thrust::complex` with `cuda::std::complex` from libcu++. Therefore, we don't plan to make any further changes to `thrust::complex`.

fwiw, I tried your repro with `cuda::std::complex` and it worked fine: https://godbolt.org/z/hrTvrK69a
