### ISSUE TITLE
Improvement: CUDA Streams + Algorithms should return "std::future<T>" opposed to implicitly synchronizing 

### ISSUE THREAD

**Issue by josephjaspers** [NVIDIA/thrust#961]
When using thrust algorithms and cuda with streams,instead of copying the memory back to the output with cudaMemcpy (causing a deviceSync) to return the values could return a std::future<T> object instead and use cudaMemcpyAsync with a callback to update the std::promise. 

IE

std::future<float>  sum = thrust::reduce(thrust::par.on(stream), begin, end);

**Comment by rconnorlawson** [comment]
I absolutely agree that thrust should allow asynchronous behavior by default when using `par.on(stream)` as an execution policy. Unavoidable synchronization after every algorithm call is a performance killer. 

I don't think many algorithms even require explicit synchronization. Sequential execution of work in a stream should be sufficient for multi-stage algorithms, for example `reduce` and `sort`. For algorithms that return a value to the CPU, futures are a good solution. The `async` namespace is still fairly incomplete, so for now it seems that there is no way to achieve asynchronous behavior in thrust for the vast majority of algorithms.

**Comment by josephjaspers** [comment]
Alternatively I would like to be able to supply the output (and therefor dodge the whole synchronization).

Does anyone know if their is a contributor's guide? I'd be willing to contribute to this personally.

**Comment by pauleonix** [comment]
Isn't this basically solved by `thrust::async` algorithms (and `par_nosync` policies)? Maybe a way for manually wrapping a CUDA stream into a `cuda::event` (in `thrust/system/cuda/future.h`) would make interoperability better?

**Comment by allisonvacanti** [comment]
The `thrust::async` algorithms were introduced several years ago to implement this solution. These are no longer being actively developed as our team has shifted focus to standardizing the [C++ Senders/Receivers proposal](https://wg21.link/P2300). This proposal provides a more CUDA-friendly approach to implementing asynchronous algorithms that avoids several of the pitfalls and complexities of using `future`-based algorithms. Our long-term goal is to provide asynchronous Thrust-like algorithms using the senders/receivers approach.

In the meantime, we recommend using the [`par_nosync` policy](https://github.com/NVIDIA/thrust/blob/main/examples/cuda/explicit_cuda_stream.cu#L40-L66). This provides asynchronous execution for several Thrust algorithms, though it is only a hint and will be ignored by algorithms that require synchronization. The [CUB device algorithms](https://nvlabs.github.io/cub/group___single_module.html) (which Thrust uses internally) are another alternative. These are inherently asynchronous and give the user far more control than the `thrust` interfaces.

Closing since we will not be supporting the `future` approach going forward, but we are actively working on an alternative solution.
